### ISSUE TITLE
Please remove the limitation on ThrottleLimit, currently set at 50

### ISSUE THREAD

**Issue by CW333** [PaulHigin/PSThreadJob#24]

**Comment by ghost** [comment]
Hitting this limitation as well. Thank you for your great work!

**Comment by ghost** [comment]
If ThrottleLimit is not passed as a parameter, 50 is used as a default. Please fix! Many thanks.

**Comment by coin8086** [comment]
That's really a limit on the excellent module! But I don't think it's a good idea to put any limit on ThrottleLimit: If I have powerful hardware, say 100GB mem, and I need a lot of parallel jobs, say 1000, you have no reason to limit it. That's exactly the problem I'm facing by the module. I'm afraid I have to fork the code and remove the limit and published one for my own use if it's not fixed soon.

**Comment by jeremytbrun** [comment]
Would like to see this limit removed as well!

**Comment by coin8086** [comment]
> Would like to see this limit removed as well!

This actually has been fixed and the issue can be closed.
