### ISSUE TITLE
Multithreading and powershell classes

### ISSUE THREAD

**Issue by brandubh** [PaulHigin/PSThreadJob#26]
Hi Paul, do you have any statement about powershell classes and PSThreadJob? From my observations if you instantiate an object in the main powershell thread and then spawn PSThread Jobs with that object as a param, the object methods are always executed in the powershell main thread, thus blocking execution of other threads. The simples way to check for it is adding a sleep in one method of the class and see what happens. I'm writing a post on how to use PSThreadJob to consume data items in a thread safe way, but this seems to break the design. Any clue? Here is the [gist](https://gist.github.com/brandubh/17e0a300f2214fac74ef04951e99f1e3) I'm working on.

Thanks in advance
Daniele

**Comment by PaulHigin** [comment]
Hi Daniele,

I apologize for the (extremely) late reply.  PowerShell classes are definitely not thread safe.  The problem is that PowerShell classes are bound to specific runspaces in which they are created.  ThreadJob uses its own runspaces to run script on other threads, and if a class instance is passed as an argument to such a job script, its behavior is undefined.  Unfortunately there is no workaround.

**Comment by brandubh** [comment]
Hi Paul, thanks for the reply, bad news for me you're confirming my fears.

Thanks

daniele

sent from a mobile device excuse typos and brevity

________________________________

**Comment by OtterKring** [comment]
Coming in quite a lot later, this might not be relevant for the thread members anymore, but for those who find this thread now there are two solutions to the problem, given on what Powershell version you are working. At the time I write this Azure Automation Runbooks for example are restricted to Powershell 7.2, so the first example is the only way to go. From Powershell 7.3 onward the second approach is the more handy one.

```
###############################
# Powershell -le 7.2

# define your class as a string variable
$classstring = @'
class ThreadClass {
    $data
    ThreadClass () {
        $this.data = 'Init'
    }
    [string] Write () {
        return $this.data
    }
}
'@

# create a scriptblock from the string and dot-source it in your code
. ( [scriptblock]::Create( $classstring ) )

# now that the class is loaded as usual, use it as you are used to in the main thread
$MyClass = [ThreadClass]::new()
$MyClass.Write()

# in foreach -parallel you have to play the same game again after importing the $classstring
1..2 | Foreach -Parallel {
    $tclassstring = $using:classstring              # import the $classstring in the thread
    . ( [scriptblock]::Create( $tclassstring ) )    # dot-source the scriptblock
    $tMyClass = [ThreadClass]::New()                # instanciate class
    "[Thread {0}] {1}" -f $_, $($tMyClass.Write())  # use thread specific class
}


###############################
# Powershell -ge 7.3

# standard class definition with the new leading NoRunspaceAffinity attribute
[NoRunspaceAffinity()]  #<--- new attribute introduced in PS 7.3
class ThreadClass {
    $data
    ThreadClass () {
        $this.data = 'Init'
    }
    [string] Write () {
        return $this.data
    }
}

# classic use of class
$MyClass = [ThreadClass]::new()
$MyClass.Write()

1..2 | Foreach -Parallel {
    $tMyClass = $using:MyClass  # import the class instance from the main code and use it as expected
    "[Thread {0}] {1}" -f $_, $($tMyClass.Write())
}
```
