### ISSUE TITLE
Add support for using variables

### ISSUE THREAD

**Issue by PaulHigin** [PaulHigin/PSThreadJob#3]
Unfortunately, PowerShell using variable processing is internal access only and so ThreadJob cannot implement it.  I am sure we can make this publicly accessible in PSCore (https://github.com/powershell/powershell), however this would mean ThreadJob would no longer be compatible with Windows PowerShell.  It seems like the solution is to have different versions of ThreadJob targeted to different versions of PowerShell.

Example:
```powershell
$var = "Hello!"
$job = Start-ThreadJob -ScriptBlock { "Output: $using:var" }
# Results in error.   Cannot use Using variable"
# Instead must use -ArgumentList or $input
$job = Start-ThreadJob -ScriptBlock { param ($var) "Output: $var" } -ArgumentList $var
$job = ($var | Start-ThreadJob -ScriptBlock { "Output: $input" })
```

**Comment by beatcracker** [comment]
Perhaps for Windows PowerShell we can make it work like Boe Prox does for PoshRSJob: [A Look at Implementing $Using: Support in PowerShell for PoshRSJob](https://learn-powershell.net/2015/05/04/a-look-at-implementing-using-support-in-powershell-for-poshrsjob/).

**Comment by PaulHigin** [comment]
Very cool.  Yes, we could definitely implement our own using variable processing, but I would rather use PowerShell's and not duplicate code.  It seems to me that this should be publicly accessible.  We can change in PSCore (I'll create an issue) but for downlevel support I agree that custom implementation is the best option.

**Comment by briantist** [comment]
[I also wrote about a quick-and-dirty method of doing `$Using:` replacement](https://www.briantist.com/how-to/use-duplicate-dsc-script-resources-in-loop/). It was for DSC Script resources but would work for anything.

I'm using RegEx (boo) but it could be updated to use AST like Boe's method.

This small function could be used by consumers in the meantime (before support is added to the module) to change scriptblocks before passing them into a ThreadJob.

**Comment by PaulHigin** [comment]
Sounds great.  I prefer the AST method.  Please feel free to submit a pull request.

**Comment by PaulHigin** [comment]
Support for Using keyword has been added.
