### ISSUE TITLE
Any release date for 2.0.0?

### ISSUE THREAD

**Issue by V-ed** [PaulHigin/PSThreadJob#34]
Hi! First of all, thanks for this module, it saves me hours of run time by running on 25000 instances in a breeze with multithreading, starting job would've cost 600 ms per instance while your thread jobs takes 25 ms. I love it!

I have seen in https://github.com/PaulHigin/PSThreadJob/pull/31 that the 2.0.0 will be coming on Powershell Gallery soon, and I would need that version for the bump on the ThrottleLimit range (I would use more than 50, basically https://github.com/PaulHigin/PSThreadJob/issues/24). Therefore, I'm wondering when is it going to be up on Powershell Gallery?

Thanks in advance!

**Comment by PaulHigin** [comment]
It should be soon.  Possibly this week but certainly next week.  I have spent a lot of time recently refactoring the repo to support a build pipeline, so that I can publish a signed module.

**Comment by PaulHigin** [comment]
ThreadJob 2.0.0 has been published.
https://www.powershellgallery.com/packages/ThreadJob/2.0.0
