### ISSUE TITLE
Suggestion: -Timeout 

### ISSUE THREAD

**Issue by Sci-Tek** [PaulHigin/PSThreadJob#35]
Currently there is no timeout value present (or im utterly blind), i've observed that jobs can have a tendancy to get stuck in running state without doing anything. impacting performance and if you get 50 jobs stuck the whole threadjob would stop.
I've not been able to figure out why the jobs seems frozen, but runtime is in the excess of 5000 seconds for a simple "invoke-command -computername remotecomputer" command. receive-job has first steps of the script so it seems to launch fine.

A -timeout parameter with a supplied number of seconds could easily mitigate the process. 

Atlernativley I workarround this by doing a do {} until loop.  

```
    get-job | where state -eq running | select id, PSBeginTime | % {
        $timeoutTime = Get-Date 
        $timeoutStartTime = $_.PSBeginTime
        $timeoutCheck = $timeoutTime - $timeoutStartTime

        if ($timeoutCheck.totalseconds -gt "$TimeoutSec") {
            $id = $_.Id
            write-warning -Message "Removed job $id due to timeout value $timeoutsec"
            Stop-Job -id $_.Id 
        }
```

**Comment by PaulHigin** [comment]
You can use Wait-Job with its timeout parameter:
```powershell
$job = Start-ThreadJob { 1..10 | % { sleep 1; "Output $_" } }
Wait-Job $job -Timeout 5
$job | Receive-Job
```
