### ISSUE TITLE
What do you do with this module when additional virtual methods are added to the base Debugger class?

### ISSUE THREAD

**Issue by KirkMunro** [PaulHigin/PSThreadJob#42]
@PaulHigin: PSThreadJob currently supports Windows PowerShell 5.1 and later. In PowerShell/PowerShell, I've added virtual methods to the base Debugger class as part of the PR I was working on to allow managing breakpoints in runspaces and remote jobs (or thread jobs once PR #41 is merged/included in PSThreadJob).

With this module being external to PowerShell (Core), what do we do when the `Debugger` base class that this module's `ThreadJobDebugger` class derives from gets additional virtual methods that you want to override? Since this requires 5.1, and that version of the base class won't have those overrides, I'm not sure what the best path forward is here, other than to have two different versions of the binary module: one for 5.x/6.x, and another for 7+.

Further, the `ThreadJobDebugger` base class implements pass-thru overrides for many methods that just call into a wrapped debugger, much like `RemotingJobDebugger`, `NestedRunspaceDebugger`, and `ServerRemoteDebugger` (although that last one uses an `ObjectRef<Debugger>` instead of just a `Debugger` for the `_wrappedDebugger` field). Wouldn't it be better to define a `RemoteRunspaceDebugger` class that handles the usage of a wrapped debugger and the invocation of wrapped debugger passthru methods in its implementation, and then derive other debuggers from that one for the few overrides in those debuggers that are needed such as `HandlePromptCommand`? Doing that would remove a lot of repeated logic, and give us an internally managed base class that could be used in binary modules external to PowerShell, allowing debuggers to be hooked up with _all_ of the overrides invoking the wrapped debugger methods regardless of the version of PowerShell being used. If we had that already, then `ThreadJobDebugger` could have derived from that, and we wouldn't need to worry about additional virtual methods being added to the base class in later versions of PowerShell because they would be automatically handled.

**Comment by PaulHigin** [comment]
I don't want to have multiple builds/versions of ThreadJob.  I feel new support for job debugging features is not as important as maintaining compatibility with Windows PowerShell 5.1.  So I don't plan to add new features that require splitting the code base.
