### ISSUE TITLE
Make $PWD default to the caller's current location in the script blocks passed to Start-ThreadJob

### ISSUE THREAD

**Issue by mklement0** [PaulHigin/PSThreadJob#46]
Following up from the discussion in https://github.com/PowerShell/PowerShell/issues/10537:

Currently, script blocks passed to `Start-ThreadJob` default to the process-wide current directory, as reflected in `[Environment]::CurrentDirectory`.

However, this is problematic, because that directory has no guaranteed or obvious relationship with the _caller's current location_.

Therefore, defaulting to the caller's current location instead is the most useful and intuitive behavior.

While technically a breaking change, my sense is that it falls into [Bucket 3: Unlikely Grey Area](https://github.com/PowerShell/PowerShell/blob/master/docs/dev-process/breaking-change-contract.md#bucket-3-unlikely-grey-area), given that the effective `$PWD` is virtually unpredictable by the user:

`$PWD` is whatever PowerShell's startup directory was - irrespective of a `-WorkingDirectory` argument passed to the CLI - or whatever in-session code that changed the process-wide current directory last set it to.

A simple example:

```powershell
PS> Set-Location /; pwsh -WorkingDirectory $HOME -noprofile -c 'Start-ThreadJob { $pwd } | Receive-Job -Wait -AutoRemove; $PWD'

Path
----
/
/Users/jdoe
```

That is, the above made `/` (or, on Windows, `C:\`) the `$PWD` for thread jobs, just because the `pwsh` instance was invoked while that directory _happened_ to have been the process-wide working directory - even though the session's  `$PWD` is `$HOME`.

**Comment by PaulHigin** [comment]
Implemented: #47
