### ISSUE TITLE
Job host output is sent directly to parent host

### ISSUE THREAD

**Issue by ajansveld** [PaulHigin/PSThreadJob#5]
Running this gives unexpected output:
```
Start-ThreadJob {1..10 |% {[System.Console]::WriteLine("$_"); sleep 1}}
```
I would argue that console output should be discarded, just like Start-Job does.

**Comment by ajansveld** [comment]
BTW - I am happy to close this issue as it appears to be non-trivial to fix and the impact is minimal.

**Comment by jazzdelightsme** [comment]
Yeah, I would say this behavior is By Design--`Start-ThreadJob` gives PS runspace isolation, but it can't possibly attempt to provide process-like isolation for process-global things. And in fact, IMO it's part of the point (proc-global things can be shared without serialization).

**Comment by ajansveld** [comment]
Agreed, closing issue.
